data_ingestion:
  bucket_name: "hotel-reservation"
  bucket_file_name: "HotelReservations.csv"
  train_ratio: 0.8

data_preprocessing:
  target_column:
    - booking_status
  categorical_columns:
    - type_of_meal_plan
    - room_type_reserved
    - market_segment_type
  numerical_columns:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - required_car_parking_space
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - repeated_guest
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
